.PHONY: build

debug-build:
	@./debug.sh debug-build

debug-non-gui:
	@./debug.sh debug-build-noshow

debug-gdb:
	@./debug.sh debug-gdb

check-frontend:
	@./debug.sh check-frontend

check-backend:
	@./debug.sh check-backend

dev-push:
	@./debug.sh push-dev

master-push:
	@./debug.sh push-master

stable-push:
	@./debug.sh push-stable

backend-test:
	@./debug.sh backend-test