[app_settings]
hide_when_closed = false
notification = true

[app_gui_settings]
background_color = "#2f3136"
foreground_color = "#ffffff"
background_button_color = "#2f3136"
foreground_button_color = "#ffffff"
background_header_table_color = "#2f3136"
foreground_header_table_color = "#ffffff"
