name: Build zClipboard on Linux

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
          image: ubuntu:22.04
          
        env:
            CI_SCRIPT: "scripts/ci_linux.sh"
            APP_NAME: "zclipboard"

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          shell: bash
          run: |
            chmod +x ${{ github.workspace }}/${{ env.CI_SCRIPT }}
            ./${{ env.CI_SCRIPT }} install-base
        
        - name: Create build directory
          shell: bash
          run: |
            ./scripts/ci_linux.sh mkdir-build
            
        - name: Build zClipboard
          shell: bash
          run: |
            ./scripts/ci_linux.sh release-build

        - name: Build AppImage
          shell: bash
          run: |
            ./${{ env.CI_SCRIPT }} image-build

        - name: Upload Release
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.APP_NAME }}
            path: ${{ env.APP_NAME }}.AppImage
