name: Deploy Lazyboard for Linux

on:
    push:
        branches: [ "master"]
      
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI_SCRIPT: "scripts/linux_deploy.sh"
            APP_NAME: "Lazyboard"

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          working-directory: ${{ github.workspace }}
          shell: bash
          run: |
            chmod +x ${{ github.workspace }}/${{ env.CI_SCRIPT }}
            ./${{ env.CI_SCRIPT }} install-dependency

        - name: Install Qt
          uses: jurplel/install-qt-action@v4

        - name: Install Rust
          shell: bash
          run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin:$PATH" >> $GITHUB_PATH

        - name: Install Rust Components
          shell: bash
          run: |
            rustup component add clippy
      
        - name: Linter Check (Rust Backend)
          shell: bash
          run: |
           make deploy-linux build_options=backend-check

        - name: Test (Rust Backend)
          shell: bash
          run: |
           make deploy-linux build_options=backend-test

        - name: Build (Rust Backend)
          shell: bash
          run:
            make deploy-linux build_options=backend-build

        - name: Build (C++ Frontend)
          shell: bash
          run: |
            make deploy-linux build_options=frontend-build

        - name: Linter Check (C++ Frontend)
          shell: bash
          run: |
            make deploy-linux build_options=frontend-check
