name: Build zClipboard for Windows

on:
  push:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Visual Studio 2019 Build Tools
        shell: powershell
        run: |
          .\scripts\ci_windows.ps1 install-vs

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: 6.5.3
            arch: win64_msvc2019_64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
            cmake-version: '3.19'

      - name: Build test for Windows
        shell: powershell
        run:
            |
          .\scripts\ci_windows.ps1 build

      - name: Deploy Qt DLL
        shell: powershell
        run: |
          .\scripts\ci_windows.ps1 deploy_qt

      - name: Upload Deployed Application
        uses: actions/upload-artifact@v4
        with:
            name: zClipboard-Windows-Release
            path: build/deploy/
