name: Build zClipboard for Windows (MSVC 2022)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 6.5.3 (MSVC 2022)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.3
          arch: win64_msvc2022_64

      - name: Install Ninja
        run: choco install ninja -y

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28'

      - name: Configure with CMake (Ninja + MSVC 2022)
        shell: bash
        env:
          QT_DIR: /d/a/zClipboard/Qt/6.5.3/msvc2022_64
        run: |
          mkdir -p build && cd build
          cmake -G "Ninja" \
            -DCMAKE_C_COMPILER=cl.exe \
            -DCMAKE_CXX_COMPILER=cl.exe \
            -DCMAKE_PREFIX_PATH="$QT_DIR" \
            ..

      - name: Build Project
        run: |
          cd build
          cmake --build .

      - name: Deploy with windeployqt
        run: |
          cd build
          "$QT_DIR/bin/windeployqt.exe" --dir ../release ../Release/zclipboard.exe

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release binary (MSVC 2022)
          path: release/