name: Build zClipboard for Windows

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: 6.5.3
            arch: win64_msvc2019_64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
            cmake-version: '3.19'
        
      - name: Test CMake
        shell: bash
        run: |
            cmake --version

      - name: Build test for Windows
        shell: bash
        run:
            |
            mkdir -p build && cd build
            cmake ..
            cmake --build . --config Release
