name: Build zClipboard for Windows

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Visual Studio 2019 Build Tools
        shell: cmd
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CMake.Project" -y --confirm --force

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: 6.5.3
            arch: win64_msvc2019_64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
            cmake-version: '3.19'

      - name: Build test for Windows
        shell: cmd
        run:
            |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
            mkdir -p build && cd build
            cmake -G "Visual Studio 16 2019" -T v142 ..
            cmake --build . --config Release
